version: "3.8"

services:
  service1:
    image: myapp:latest
    ports:
      - "3000:3000"  # Map port 3000 on the host to 3000 in the container
    deploy:
      replicas: 3
    environment:
      - PORT=3000  # Set port for Service 1

  service2:
    image: myapp:latest
    ports:
      - "3001:3001"  # Map port 3001 on the host to 3001 in the container
    deploy:
      replicas: 2
    environment:
      - PORT=3001  # Set port for Service 2
